var type_texts = [
    "A penny saved is a penny earned.",
    "Never look back. They might be gaining on you.",
    "A stitch in time saves nine.",
    "The only thing you have to fear is fear itself.",
    "The rate at which inflation is increasing is decreasing.",
    "Rubber baby buggy bumpers.",
    "One must never contradict an active love",
    "Nobody knows, the troubles I've seen",
    "e4 is best by test.",
    "A man, a plan, a canal. Panama.",
    "Not much of a math game really is it",
    "Rome wasn't built in a day.",
    "Venmo me your lunch money, nerd.",
    "We accept the love we think we deserve.",
    "Love all, trust a few, do wrong to none.",
    "Lorem ipsum dolor sit amet.",
    "My name is Ozymandias, King of Kings.",
    "Look on my Works, ye Mighty, and despair!",
    "To be or not to be: that is the question.",
    "O, what a rogue and peasant slave am I.",
    "I wandered lonely as a cloud",
    "Able was I, ere I saw Elba.",
    "Rats live on no evil star.",
    "A proper copper coffee pot.",
    "We surely shall see the sun shine soon.",
    "Three grey geese in green fields grazing.",
    "The sixth Sheik's sixth sheep is sick.",
    "The instinct of an extinct insect stinks.",
    "Irish wristwatch, Swiss wristwatch.",
    "Mathematics is the gate and key to the sciences.",
    "The secret of getting ahead is getting started.",
    "Simplicity is the key to brilliance.",
    "Hello, my friend. Care for a drink?",

]

var long_texts = [
    "\"I would rather die of passion than of boredom.\" - Vincent van Gogh",
    "\"Dreaming, after all, is a form of planning.\" - Gloria Steinem",
    "\"I have no special talent. I am only passionately curious.\" - Albert Einstein",
    "\"Wisely, and slow. They stumble that run fast.\" - William Shakespeare",
    "\"There are no prime numbers except for 57.\" - Grothendieck",
    "\"You miss 100% of the shots you don't take.\" - Wayne Gretzky",
    "Now I will do what others won't, so tomorrow I can do what others can't.",
    "\"Dream big and dare to fail.\" - Norman Vaughan",
    "The proof is trivial and is left as an exercise to the reader.",
    "What do you mean my intuition doesn't constitute a rigorous proof?",
    "Why didn't Newton discover group theory? He wasn't Abel!",
    "A topologist playing poker: \"Man, I fold.\"",
    "To see the world in a grain of sand and heaven in wild flower",
    "Two roads diverged in a wood, and I - I took the road less traveled by",
    "I have loved the stars too fondly to be fearful of the night.",
    "Only those who will risk going too far can possibly find out how far one can go.",
    "This is the way the world ends: Not with a bang but a whimper",
    "If you have the words, there's always a chance that you'll find the way.",
    "Poetry is what gets lost in translation.",
    "If you ain't cheating, you ain't trying.",
    "Poetry is what happens when nothing else can.",
    "I like this place and could willingly waste my time in it.",
    "In a minute there is time for decisions and revisions which a minute will reverse.",
    "I have drunken deep of joy, and I will taste no other wine tonight.",
    "Poetry might be defined as the clear expression of mixed feelings.",
    "I am awaiting perpetually and forever a renaissance of wonder",
    "Poetry is eternal graffiti written in the heart of everyone.",
    "Poetry is the shadow cast by our streetlight imaginations.",
    "\"Do not worry about your difficulties in Mathematics.\" - Albert Einstein",
    "\"Mathematics is written for mathematicians.\" - Copernicus",
    "\"There should be no such thing as boring mathematics.\" - Dijkstra",
    "\"The only way to learn mathematics is to do mathematics.\" - Halmos",
    "\"The essence of mathematics lies in its freedom.\" - Cantor",
    "\"Wherever there is number, there is beauty.\" - Proclus",
    "\"Somebody had to be great, so why not me?\" - Deshaun Watson",
    "Impossible is a word to be found only in the dictionary of fools.",
    "It is hard to fail but it is worse never to have tried to succeed.",
    "I have not failed. I’ve just found 10,000 ways that won’t work.",
    "It does not do to dwell on dreams and forget to live.",
    "If you don’t stand for something you will fall for anything.",
    "If you can’t explain it to a six year old, you don’t understand it yourself.",
    "In three words I can sum up everything I’ve learned about life: It Goes On.",
    "Don’t cry because it’s over, smile because it happened."
]